work_dir: ./output/result/ctrgcn_V1_J

# feeder
feeder: dataset.feeder.Feeder
train_feeder_args: 
  data_path: /home/zjl_laoshi/xiaoke/Top/Test_dataset/save_2d_pose/joint.npz
  # label_path : /home/zjl_laoshi/xiaoke/Top/Test_dataset/save_2d_pose/train_label.npz
  data_split: train
  p_interval: [0.5, 1]
  window_size: 64
  bone: False
  vel: False
  
test_feeder_args:
  data_path: /home/zjl_laoshi/xiaoke/Top/Test_dataset/save_2d_pose/test_B_joint.npz #train
  # data_path: /home/zjl_laoshi/xiaoke/Top/Test_dataset/save_2d_pose/test_A_joint.npz #test
  data_split: test
  p_interval: [0.95]
  window_size: 64
  bone: False
  vel: False


model: model.ctrgcn_xy.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.Simcc.Graph
  graph_args:
    labeling_mode: 'spatial'


#optim
# weight_decay: 0.0004
weight_decay: 0.0008
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: 4 5
batch_size: 64
test_batch_size: 64
num_epoch: 65            # 65

