work_dir: ./output/result/ctrgcn_V1_J_3D

# feeder
feeder: dataset.feeder_xyz.Feeder
train_feeder_args: 
  data_path: /home/zjl_laoshi/xiaoke/Top/Test_dataset/save_3d_pose/joint.npz
  data_split: train
  p_interval: [0.5, 1]
  window_size: 64
  bone: False
  vel: False

test_feeder_args:
  # data_path: /home/zjl_laoshi/xiaoke/Top/Test_dataset/save_3d_pose/test_A_bone.npz #train
  data_path: /home/zjl_laoshi/xiaoke/Top/Test_dataset/save_3d_pose/test_B_bone.npz #test
  data_split: test
  p_interval: [0.95]
  window_size: 64
  bone: False
  vel: False

# model
model: model.ctrgcn_xyz.Model
model_args:
  num_class: 155
  num_point: 17
  num_person: 2
  graph: graph.Simcc.Graph
  graph_args:
    labeling_mode: 'spatial'

#optim
weight_decay: 0.0008
base_lr: 0.1
lr_decay_rate: 0.1
step: [35, 55]
warm_up_epoch: 5

# training
device: [3, 4]
batch_size: 128
test_batch_size: 128
num_epoch: 65
nesterov: True
